resources:
  pipelines:
    healthcare_pipeline_combined:

      name: healthcare-pipeline_combined-${bundle.target}

      catalog: ${var.catalog}
      schema: ${var.schema}

      development: ${var.pipeline_development}

      continuous: false
      serverless: true

      libraries:
        - file:
            path: ../src/bronze.py

        - file:
            path: ../src/silver.py

        - file:
            path: ../src/gold.py

        - file:
            path: ../src/audit.py

        - file:
            path: ../src/transformations/03_silver_claims_cdc.py

        - file:
            path: ../src/transformations/04_advanced_claims_pipeline.py